apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: jaeger
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: debug
          image: jaegertracing/all-in-one:latest
          name: jaeger
          ports:
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
      restartPolicy: Always
