apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: nats
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nats
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: nats
    spec:
      containers:
        - args:
            - --cluster_name
            - NATS
            - --server_name=S1-NATS
            - --cluster
            - nats://0.0.0.0:6222
            - --routes=nats://ruser:T0pS3cr3t@nats-1:6222,nats://ruser:T0pS3cr3t@nats-2:6222
            - --m
            - "8222"
            - --js
            - --sd=/data
          image: nats
          name: nats
          ports:
            - containerPort: 8222
              protocol: TCP
            - containerPort: 4222
              protocol: TCP
            - containerPort: 6222
              protocol: TCP
      restartPolicy: Always
