apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: postgres-exporter
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-exporter
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: postgres-exporter
    spec:
      containers:
        - env:
            - name: DATA_SOURCE_NAME
              value: postgresql://postgres:admin@postgres:5432/users?sslmode=disable
          image: prometheuscommunity/postgres-exporter
          name: postgres-exporter
          ports:
            - containerPort: 9187
              protocol: TCP
      restartPolicy: Always
