apiVersion: v1
data:
  db-compose.yaml: ""
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets: []
          scheme: http
          timeout: 10s
          api_version: v1
    scrape_configs:
      - job_name: prometheus
        honor_timestamps: true
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - host.docker.internal:8080
              - host.docker.internal:9187
              - host.docker.internal:7777
              - host.docker.internal:7778
              - host.docker.internal:7779
              - host.docker.internal:9121
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
