apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: prometheus-nats-exporter
  name: prometheus-nats-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus-nats-exporter
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: prometheus-nats-exporter
    spec:
      containers:
        - args:
            - -connz
            - -varz
            - -healthz
            - -D
            - -jsz=all
            - http://host.docker.internal:8222
          image: natsio/prometheus-nats-exporter
          name: prometheus-nats-exporter
          ports:
            - containerPort: 7777
              protocol: TCP
      hostname: prometheus-nats-exporter
      restartPolicy: Always
