apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: prometheus-nats-exporter
  name: prometheus-nats-exporter
spec:
  ports:
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    io.kompose.service: prometheus-nats-exporter
